spring.application.name=user-service

# PostgreSQL
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${POSTRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASS:specialpassword!}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.sql.init.mode=always

# JWT Config
jwt.secret=${JWT_SECRET:mySuperSecretKeyThatIsLongEnough12345}
jwt.expirationMs=${JWT_EXPIRATION_MS:3600000}

# Admin User Config
app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD:admin}
app.admin.email=${ADMIN_EMAIL:admin@biteful.com}

# CORS Config
cors.allowed.origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}