spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=specialpassword!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always

jwt.secret=${JWT_SECRET:mySuperSecretKeyThatIsLongEnough12345}
jwt.expirationMs=${JWT_EXPIRATION_MS:3600000}

app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD:admin}
app.admin.email=${ADMIN_EMAIL:admin@biteful.com}