apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipe-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
  labels:
    app: recipe-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
        - name: recipe-service
          image: recipe-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          volumeMounts:
            - name: uploads-volume
              mountPath: /uploads

          env:
            - name: MONGO_URI
              value: mongodb://mongodb:specialpassword!@mongodb:27017/admin

            - name: JWT_SECRET
              value: mySuperSecretKeyThatIsLongEnough12345

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: recipe-uploads-pvc