spring.application.name=recipe-service

spring.mongodb.uri=${MONGO_URI:mongodb://mongodb:specialpassword!@localhost:27017}
spring.mongodb.database=recipeDB
spring.mongodb.representation.uuid=standard
spring.data.mongodb.auto-index-creation=true

jwt.secret=${JWT_SECRET:mySuperSecretKeyThatIsLongEnough12345}

cors.allowed.origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Recipe generation
gemini.api.key=${GEMINI_API_KEY:NO_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent