spring.application.name=recipe-service

# MongoDB
spring.mongodb.uri=${MONGO_URI:mongodb://mongodb:specialpassword!@localhost:27017}
spring.mongodb.database=recipeDB
spring.mongodb.representation.uuid=standard
spring.data.mongodb.auto-index-creation=true

# PostgresSQL
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${POSTRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASS:specialpassword!}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.sql.init.mode=always

# JWT Config
jwt.secret=${JWT_SECRET:mySuperSecretKeyThatIsLongEnough12345}

# CORS Config
cors.allowed.origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}

# Image Size Config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Recipe generation API Config
gemini.api.key=${GEMINI_API_KEY:NO_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent