version: '3.1'

services:

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: biteful
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: specialpassword!
    volumes:
      - postgres_biteful:/var/lib/postgresql/data

  user-service:
    image: user-service:latest
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/biteful
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: specialpassword!
      JWT_SECRET: mySuperSecretKeyThatIsLongEnough12345
    ports:
      - "8080:8080"

volumes:
  postgres_biteful: