apiVersion: apps/v1
kind: Deployment
metadata:
  name: list-service
  labels:
    app: list-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: list-service
  template:
    metadata:
      labels:
        app: list-service
    spec:
      containers:
        - name: list-service
          image: mariusjugaru/list-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/biteful

            - name: SPRING_DATASOURCE_USERNAME
              value: postgres

            - name: SPRING_DATASOURCE_PASSWORD
              value: specialpassword!

            - name: JWT_SECRET
              value: mySuperSecretKeyThatIsLongEnough12345

            - name: CORS_ALLOWED_ORIGIN
              value: https://biteful.xyz

            - name: API_URL
              value: https://api.biteful.xyz

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"