apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: mariusjugaru/user-service:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080

        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres:5432/biteful

          - name: SPRING_DATASOURCE_USERNAME
            value: postgres

          - name: SPRING_DATASOURCE_PASSWORD
            value: specialpassword!

          - name: JWT_SECRET
            value: mySuperSecretKeyThatIsLongEnough12345

          - name: CORS_ALLOWED_ORIGIN
            value: https://d3b9r33ziyhoy4.cloudfront.net

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
